import pandas as pd


def etna_observable_metadata():
    rows = [
        # ME01 waveform-derived variables
        {
            "case": "Etna",
            "source_id": "ME01",
            "source_label": "ME01 seismic station",
            "observable": "teleseismic_band",
            "observable_label": "Teleseismic-band energy, 0.05–0.5 Hz",
            "family": "seismic",
            "spatial_type": "point_station",
            "lat": None,
            "lon": None,
            "plot_role": "direct_measurement",
        },
        {
            "case": "Etna",
            "source_id": "ME01",
            "source_label": "ME01 seismic station",
            "observable": "background_seismic",
            "observable_label": "Background seismic energy, 0.5–4 Hz",
            "family": "seismic",
            "spatial_type": "point_station",
            "lat": None,
            "lon": None,
            "plot_role": "direct_measurement",
        },
        {
            "case": "Etna",
            "source_id": "ME01",
            "source_label": "ME01 seismic station",
            "observable": "effect_seismic",
            "observable_label": "High-frequency seismic response, 4–12 Hz",
            "family": "seismic_effect",
            "spatial_type": "point_station",
            "lat": None,
            "lon": None,
            "plot_role": "effect",
        },

        # ME02 waveform-derived variables
        {
            "case": "Etna",
            "source_id": "ME02",
            "source_label": "ME02 seismic station",
            "observable": "teleseismic_band",
            "observable_label": "Teleseismic-band energy, 0.05–0.5 Hz",
            "family": "seismic",
            "spatial_type": "point_station",
            "lat": None,
            "lon": None,
            "plot_role": "direct_measurement",
        },
        {
            "case": "Etna",
            "source_id": "ME02",
            "source_label": "ME02 seismic station",
            "observable": "background_seismic",
            "observable_label": "Background seismic energy, 0.5–4 Hz",
            "family": "seismic",
            "spatial_type": "point_station",
            "lat": None,
            "lon": None,
            "plot_role": "direct_measurement",
        },
        {
            "case": "Etna",
            "source_id": "ME02",
            "source_label": "ME02 seismic station",
            "observable": "effect_seismic",
            "observable_label": "High-frequency seismic response, 4–12 Hz",
            "family": "seismic_effect",
            "spatial_type": "point_station",
            "lat": None,
            "lon": None,
            "plot_role": "effect",
        },

        # Etna gas/meteo variables
        {
            "case": "Etna",
            "source_id": "ETNAGAS_3",
            "source_label": "Etna gas/meteo station 3",
            "observable": "CO2_3",
            "observable_label": "Soil CO₂ concentration",
            "family": "gas",
            "spatial_type": "point_or_network_station",
            "lat": None,
            "lon": None,
            "plot_role": "direct_or_network_measurement",
        },
        {
            "case": "Etna",
            "source_id": "ETNAGAS_3",
            "source_label": "Etna gas/meteo station 3",
            "observable": "AirTemp_3",
            "observable_label": "Air temperature",
            "family": "meteorology",
            "spatial_type": "point_or_network_station",
            "lat": None,
            "lon": None,
            "plot_role": "direct_or_network_measurement",
        },
        {
            "case": "Etna",
            "source_id": "ETNAGAS_3",
            "source_label": "Etna gas/meteo station 3",
            "observable": "pressure_drop",
            "observable_label": "Atmospheric pressure drop",
            "family": "meteorology",
            "spatial_type": "point_or_network_station",
            "lat": None,
            "lon": None,
            "plot_role": "direct_or_network_measurement",
        },
        {
            "case": "Etna",
            "source_id": "ETNAGAS_3",
            "source_label": "Etna gas/meteo station 3",
            "observable": "WindSpeed",
            "observable_label": "Wind speed",
            "family": "meteorology",
            "spatial_type": "point_or_network_station",
            "lat": None,
            "lon": None,
            "plot_role": "direct_or_network_measurement",
        },

        # Etna proxy/source observables
        {
            "case": "Etna",
            "source_id": "ETNA_OPENMETEO_PROXY",
            "source_label": "Open-Meteo Etna proxy point",
            "observable": "API",
            "observable_label": "Antecedent precipitation index",
            "family": "weather_proxy",
            "spatial_type": "proxy_point",
            "lat": 37.75,
            "lon": 14.99,
            "plot_role": "proxy",
        },
        {
            "case": "Etna",
            "source_id": "ETNA_SUMMIT_PLUME",
            "source_label": "Etna summit plume proxy",
            "observable": "CO2_SO2",
            "observable_label": "Plume CO₂/SO₂ ratio",
            "family": "gas_plume",
            "spatial_type": "source_region_proxy",
            "lat": None,
            "lon": None,
            "plot_role": "source_proxy",
        },
    ]

    return pd.DataFrame(rows)